name: Desktop Build

on:
  push:
    branches: ["main"]

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run package
      - uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: dist

